apiVersion: apps/v1
kind: Deployment
metadata:
  name:  api-gateway
  namespace: default
  labels:
    app: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  api-gateway
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  api-gateway
        image:  080196/microservice
        ports:
          - name: http
            containerPort:  3000
            protocol:  TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
          - name: SERVICES
            value: api
          - name: PORT
            value: "3000"
        envFrom:
          - configMapRef:
              name: microservice-cm
      restartPolicy: Always